### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [abbychen0427/git-workshop#1]
readme 上放得那張圖實在太讚啦，讓我想到瘋狂加班的工程師（咦）

影片的心得也很棒， 學習除了 input 外，更需要的是 output，能整理資訊、並且在用自己的觀點紀錄一次心得，這不是容易的事，接下來的課程作業中，都還會有類似的安排，繼續保持！

**Comment by abbychen0427** [comment]
感謝老師的feedback! 我自己也很喜歡那張動圖ＸＤ期待未來的分享影片！
